"""
Streamlit frontend for Sprint Engine — IDE-style layout.
Requires the FastAPI backend running on http://127.0.0.1:8001.
Start with:  streamlit run streamlit_app.py
"""

from __future__ import annotations

import html as html_mod
import re as _re
from datetime import datetime

import requests
import streamlit as st
import streamlit.components.v1 as components

API_BASE = "http://127.0.0.1:8001"

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(page_title="Sprint Engine", page_icon="🚀", layout="wide", initial_sidebar_state="collapsed")

# ── Session state defaults ───────────────────────────────────────────────────
for key, default in [
    ("chat_history", []), ("chat_mode", "auto"), ("active_view", "tasks"),
    ("report_content", ""), ("report_loaded", False), ("table_sort", "status"),
]:
    if key not in st.session_state:
        st.session_state[key] = default

# ── API helpers ──────────────────────────────────────────────────────────────
def api_get(path: str):
    try:
        r = requests.get(f"{API_BASE}{path}", timeout=15)
        return r.json() if r.ok else None
    except requests.ConnectionError:
        return None


def api_post(path: str, body: dict | None = None, method: str = "POST"):
    try:
        if method == "DELETE":
            r = requests.delete(f"{API_BASE}{path}", timeout=30)
        else:
            r = requests.post(f"{API_BASE}{path}", json=body or {}, timeout=60)
        return r.json(), r.ok
    except requests.ConnectionError:
        return {"detail": "Backend not reachable. Is the FastAPI server running?"}, False


# ── Constants ────────────────────────────────────────────────────────────────
LIGHT_EMOJI = {"green": "🟢", "yellow": "🟡", "red": "🔴"}
STATUS_EMOJI = {
    "done": "✅", "in_progress": "🚧", "on_hold": "⏸️",
    "follow_up": "🔁", "blocked": "⛔", "not_started": "⚪",
}
STATUS_RANK = {"blocked": 0, "in_progress": 1, "on_hold": 2, "follow_up": 3, "not_started": 4, "done": 5}
STATUS_COLORS = {
    "blocked": "#ff6b6b", "in_progress": "#ffd43b", "on_hold": "#a9a9a9",
    "follow_up": "#74c0fc", "not_started": "#868e96", "done": "#51cf66",
}

def esc(v: str) -> str:
    return html_mod.escape(str(v or ""))

def pretty_status(status: str) -> str:
    text = (status or "").replace("_", " ").strip().title()
    return "Completed" if text == "Done" else text

def pretty_eta(eta: str) -> str:
    return (eta or "").strip() or "-"

def add_chat(role: str, text: str):
    st.session_state.chat_history.append({"role": role, "text": text})


DEFAULT_SYSTEM_PROMPT = """For the following categories I need an excerpt based on the below information:

1. The excerpt should be in Turkish language.
2. The excerpt must highlight the main USP of a specific brand in connection to the respective category. Like Samsung Air conditioner should focus on the latest USP being pushed from Samsung in 2026 for Air conditioners. This can be technology, mechanical change, size change, or any other promotable USP.
3. The excerpt must not exceed 150 words.
4. The excerpt should not use repetitive sentence structure for different pages.
5. The excerpt should give an advertising feel and not by any chance feel like it is generated by AI.
6. The excerpt should follow proper Turkish semantics and grammatical structure.
7. This excerpt will be placed on the landing pages for each of the brand+category combination."""


def render_streamlit_content_generator() -> None:
    st.markdown("#### Content Generator")

    if "cg_system_prompt" not in st.session_state:
        st.session_state.cg_system_prompt = DEFAULT_SYSTEM_PROMPT
    if "cg_output" not in st.session_state:
        st.session_state.cg_output = ""

    col_left, col_right = st.columns([1, 1], gap="large")

    with col_left:
        st.markdown("**System Prompt**")
        system_prompt = st.text_area(
            label="system_prompt",
            value=st.session_state.cg_system_prompt,
            height=300,
            label_visibility="collapsed",
            key="cg_system_prompt_area",
        )

        st.markdown("**Input Context**")
        input_context = st.text_area(
            label="input_context",
            height=280,
            placeholder="Paste brand, category, product details here...",
            label_visibility="collapsed",
            key="cg_input_context_area",
        )

        c1, c2 = st.columns([1, 1])
        with c1:
            generate_clicked = st.button("Generate", type="primary", use_container_width=True, key="cg_generate")
        with c2:
            clear_clicked = st.button("Clear", use_container_width=True, key="cg_clear")

    with col_right:
        st.markdown("**Generated Excerpt**")

        if clear_clicked:
            st.session_state.cg_output = ""
            st.session_state.cg_system_prompt = system_prompt
            st.rerun()

        if generate_clicked:
            if not (input_context or "").strip():
                st.warning("Please enter input context before generating.")
            else:
                with st.spinner("Generating excerpt…"):
                    data, ok = api_post(
                        "/api/content/generate-excerpt",
                        {"system_prompt": system_prompt, "input_context": input_context},
                    )
                if ok and data.get("ok"):
                    st.session_state.cg_output = data.get("excerpt", "")
                    st.session_state.cg_system_prompt = system_prompt
                elif not ok:
                    err = data.get("detail") or data.get("error") or "Unknown error"
                    st.error(f"Error: {err}")
                else:
                    err = data.get("error") or data.get("detail") or "Unknown error"
                    st.error(f"Error: {err}")

        output = st.text_area(
            label="output",
            value=st.session_state.cg_output,
            height=560,
            label_visibility="collapsed",
            key="cg_output_area",
        )

        if st.session_state.cg_output:
            if st.button("Copy to Clipboard", key="cg_copy"):
                st.markdown(
                    f"""<script>navigator.clipboard.writeText({repr(st.session_state.cg_output)});</script>""",
                    unsafe_allow_html=True,
                )
                st.toast("Copied!", icon="✅")


def render_streamlit_prds() -> None:
    st.markdown("#### PRDs")
    st.caption("Upload PDF PRDs — text is extracted, chunked, and fed into the knowledge graph automatically.")

    # Upload form
    with st.form("prd_upload_form", clear_on_submit=True):
        title = st.text_input("PRD Title", placeholder="e.g. Q2 SEO Strategy")
        uploaded_file = st.file_uploader("PDF File", type=["pdf"])
        submitted = st.form_submit_button("Upload PDF", type="primary")
        if submitted:
            if not title.strip():
                st.warning("Please enter a title.")
            elif uploaded_file is None:
                st.warning("Please select a PDF file.")
            else:
                import requests as _requests  # noqa: PLC0415
                try:
                    base = "http://127.0.0.1:8001"
                    resp = _requests.post(
                        f"{base}/api/prds",
                        data={"title": title.strip()},
                        files={"file": (uploaded_file.name, uploaded_file.read(), "application/pdf")},
                        timeout=60,
                    )
                    if resp.ok:
                        d = resp.json()
                        st.success(f"Uploaded '{d['title']}' — {d['chunk_count']} chunks. Knowledge enrichment running in background.")
                        st.rerun()
                    else:
                        detail = resp.json().get("detail", "Upload failed.")
                        st.error(f"Error: {detail}")
                except Exception as exc:
                    st.error(f"Upload failed: {exc}")

    st.divider()

    # PRD list
    data = api_get("/api/prds")
    prds = data.get("prds", []) if data else []

    if not prds:
        st.info("No PRDs uploaded yet.")
        return

    for prd in prds:
        prd_id = prd.get("id", "")
        with st.expander(f"📄 {prd.get('title', prd_id)}  ·  {prd.get('chunk_count', 0)} chunks  ·  {prd.get('uploaded_at', '')[:10]}", expanded=False):
            col_del, _ = st.columns([1, 5])
            with col_del:
                if st.button("Delete", key=f"del_prd_{prd_id}", type="secondary"):
                    _, dok = api_post(f"/api/prds/{prd_id}", method="DELETE")
                    if dok:
                        st.toast("PRD removed.", icon="🗑️")
                        st.rerun()

            # Load rules + graph
            detail_data = api_get(f"/api/prds/{prd_id}/rules")
            if not detail_data:
                st.warning("Could not load PRD details.")
                continue

            graph = detail_data.get("graph", {})
            nodes = graph.get("nodes", [])
            edges = graph.get("edges", [])

            if not nodes:
                st.caption("No entities extracted from this PRD yet. Synthesis runs in background — check back in a moment.")
            else:
                import json as _json  # noqa: PLC0415
                nodes_js = _json.dumps(nodes)
                edges_js = _json.dumps(edges)
                graph_html = f"""<!DOCTYPE html><html><head>
<style>
*{{box-sizing:border-box;margin:0;padding:0;}}
body{{background:#19171d;overflow:hidden;font-family:Segoe UI,sans-serif;}}
#wrap{{position:relative;width:100%;height:480px;}}
svg{{display:block;width:100%;height:480px;background:#19171d;cursor:grab;}}
#tip{{display:none;position:absolute;top:10px;right:10px;width:230px;background:#1e1c24;
  border:1px solid #3f3a49;border-radius:10px;padding:12px 14px;font-size:12px;color:#e5e1ec;z-index:10;}}
.tip-close{{position:absolute;top:7px;right:10px;background:none;border:none;color:#7c6f9e;cursor:pointer;font-size:14px;}}
.tip-type{{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#7c6f9e;margin-bottom:3px;}}
.tip-name{{font-size:14px;font-weight:700;margin-bottom:6px;}}
.tip-desc{{font-size:11px;color:#a89ec0;line-height:1.5;margin-bottom:8px;}}
.tip-rl{{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#7c6f9e;margin-bottom:3px;}}
.tip-rel{{font-size:11px;color:#c4bcd8;padding:2px 0;}}
.tip-relt{{color:#a78bfa;font-style:italic;}}
</style></head><body>
<div id="wrap">
  <svg id="g"><g id="zg"></g></svg>
  <div id="tip"><button class="tip-close" onclick="document.getElementById('tip').style.display='none'">✕</button>
    <div id="tip-content"></div></div>
</div>
<script>
(function(){{
  const nodes={nodes_js},edges={edges_js};
  const colors={{team:"#a78bfa",system:"#60a5fa",topic:"#34d399",constraint:"#f87171",process:"#fbbf24",feature:"#fb923c"}};
  const svg=document.getElementById("g"),zg=document.getElementById("zg"),tip=document.getElementById("tip"),tc=document.getElementById("tip-content");
  const W=svg.clientWidth||900,H=480,CX=W/2,CY=H/2;
  svg.setAttribute("viewBox",`0 0 ${{W}} ${{H}}`);
  const pos=nodes.map((_,i)=>{{const a=(i/nodes.length)*2*Math.PI,r=Math.min(W,H)*0.32;return{{x:CX+r*Math.cos(a),y:CY+r*Math.sin(a),vx:0,vy:0}};}});
  const idx={{}};nodes.forEach((n,i)=>idx[n.id]=i);
  for(let t=0;t<160;t++){{
    for(let i=0;i<pos.length;i++)for(let j=i+1;j<pos.length;j++){{
      const dx=pos[i].x-pos[j].x,dy=pos[i].y-pos[j].y,d=Math.max(1,Math.sqrt(dx*dx+dy*dy)),f=1800/(d*d);
      pos[i].vx+=(dx/d)*f;pos[i].vy+=(dy/d)*f;pos[j].vx-=(dx/d)*f;pos[j].vy-=(dy/d)*f;
    }}
    edges.forEach(e=>{{const si=idx[e.source],ti=idx[e.target];if(si==null||ti==null)return;
      const dx=pos[ti].x-pos[si].x,dy=pos[ti].y-pos[si].y,d=Math.max(1,Math.sqrt(dx*dx+dy*dy)),f=(d-110)*0.035;
      pos[si].vx+=(dx/d)*f;pos[si].vy+=(dy/d)*f;pos[ti].vx-=(dx/d)*f;pos[ti].vy-=(dy/d)*f;
    }});
    pos.forEach(p=>{{p.vx+=(CX-p.x)*0.01;p.vy+=(CY-p.y)*0.01;}});
    pos.forEach(p=>{{p.x=Math.max(60,Math.min(W-60,p.x+p.vx*0.5));p.y=Math.max(30,Math.min(H-30,p.y+p.vy*0.5));p.vx*=0.72;p.vy*=0.72;}});
  }}
  const ns="http://www.w3.org/2000/svg";
  edges.forEach(e=>{{const si=idx[e.source],ti=idx[e.target];if(si==null||ti==null)return;
    const l=document.createElementNS(ns,"line");
    l.setAttribute("x1",pos[si].x.toFixed(1));l.setAttribute("y1",pos[si].y.toFixed(1));
    l.setAttribute("x2",pos[ti].x.toFixed(1));l.setAttribute("y2",pos[ti].y.toFixed(1));
    l.setAttribute("stroke","#4a4356");l.setAttribute("stroke-width","1.4");l.setAttribute("opacity","0.7");
    zg.appendChild(l);
    const lt=document.createElementNS(ns,"text");
    lt.setAttribute("x",((pos[si].x+pos[ti].x)/2).toFixed(1));lt.setAttribute("y",((pos[si].y+pos[ti].y)/2).toFixed(1));
    lt.setAttribute("text-anchor","middle");lt.setAttribute("font-size","8");lt.setAttribute("fill","#6b5f8a");lt.setAttribute("pointer-events","none");
    lt.textContent=e.relation_type.replace(/_/g," ");zg.appendChild(lt);
  }});
  nodes.forEach((n,i)=>{{
    const c=colors[n.entity_type]||"#9ca3af",g=document.createElementNS(ns,"g");
    g.style.cursor="pointer";
    const ci=document.createElementNS(ns,"circle");
    ci.setAttribute("cx",pos[i].x.toFixed(1));ci.setAttribute("cy",pos[i].y.toFixed(1));
    ci.setAttribute("r","9");ci.setAttribute("fill",c);ci.setAttribute("stroke","#19171d");ci.setAttribute("stroke-width","1.5");
    const tx=document.createElementNS(ns,"text");
    const lb=(n.name||"").length>20?n.name.slice(0,19)+"…":n.name;
    tx.setAttribute("x",pos[i].x.toFixed(1));tx.setAttribute("y",(pos[i].y+21).toFixed(1));
    tx.setAttribute("text-anchor","middle");tx.setAttribute("font-size","10");tx.setAttribute("fill","#e5e1ec");
    tx.setAttribute("stroke","#19171d");tx.setAttribute("stroke-width","2.5");tx.setAttribute("paint-order","stroke");tx.setAttribute("pointer-events","none");
    tx.textContent=lb;
    g.addEventListener("mouseenter",()=>{{ci.setAttribute("r","11");ci.setAttribute("stroke",c);}});
    g.addEventListener("mouseleave",()=>{{ci.setAttribute("r","9");ci.setAttribute("stroke","#19171d");}});
    g.addEventListener("click",ev=>{{
      ev.stopPropagation();
      const rels=edges.filter(e=>e.source===n.id||e.target===n.id).map(e=>{{
        const oid=e.source===n.id?e.target:e.source,oname=(nodes.find(x=>x.id===oid)||{{}}).name||oid;
        return `<div class="tip-rel">${{e.source===n.id?"→":"←"}} <span class="tip-relt">${{e.relation_type.replace(/_/g," ")}}</span> ${{oname}}</div>`;
      }}).join("");
      tc.innerHTML=`<div class="tip-type">${{n.entity_type}}</div><div class="tip-name">${{n.name}}</div>${{n.description?`<div class="tip-desc">${{n.description}}</div>`:""}}`+(rels?`<div class="tip-rl">Relations</div>`+rels:"");
      tip.style.display="block";
    }});
    g.appendChild(ci);g.appendChild(tx);zg.appendChild(g);
  }});
  svg.addEventListener("click",()=>{{tip.style.display="none";}});
  let tx2=0,ty=0,sc=1;
  const ap=()=>zg.setAttribute("transform",`translate(${{tx2}},${{ty}}) scale(${{sc}})`);
  svg.addEventListener("wheel",e=>{{e.preventDefault();const f=e.deltaY<0?1.12:0.89,r=svg.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;tx2=mx-(mx-tx2)*f;ty=my-(my-ty)*f;sc*=f;ap();}},{{passive:false}});
  let drag=false,dx0,dy0,tx3,ty3;
  svg.addEventListener("mousedown",e=>{{drag=true;dx0=e.clientX;dy0=e.clientY;tx3=tx2;ty3=ty;svg.style.cursor="grabbing";}});
  window.addEventListener("mousemove",e=>{{if(!drag)return;tx2=tx3+(e.clientX-dx0);ty=ty3+(e.clientY-dy0);ap();}});
  window.addEventListener("mouseup",()=>{{drag=false;svg.style.cursor="grab";}});
}})();
</script></body></html>"""
                components.html(graph_html, height=490, scrolling=False)


def render_streamlit_knowledge_alt() -> None:
    st.markdown("#### Entity Knowledge Graph")
    html_payload = """
    <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #111; font-family: Segoe UI, sans-serif; color: #d4d4d4; }
    #root { display: flex; flex-direction: column; height: 1160px; }
    #toolbar {
      display: flex; gap: 6px; flex-wrap: wrap; align-items: center;
      padding: 8px 12px; background: #0a0a0a; border-bottom: 1px solid #2a2a2a; flex-shrink: 0;
    }
    #toolbar select, #toolbar input {
      background: #111; color: #d4d4d4; border: 1px solid #333;
      border-radius: 8px; padding: 5px 8px; font-size: 12px; font-family: inherit;
    }
    #toolbar input { flex: 1; min-width: 200px; }
    #refreshBtn, #rebuildBtn, #synthesizeBtn, #refineBtn {
      background: #1f2937; color: #d4d4d4; border: 1px solid #374151;
      border-radius: 8px; padding: 5px 14px; cursor: pointer; font-size: 12px;
      font-family: inherit; white-space: nowrap;
    }
    #refreshBtn:hover, #rebuildBtn:hover, #synthesizeBtn:hover, #refineBtn:hover { background: #374151; }
    #refreshBtn:disabled, #rebuildBtn:disabled, #synthesizeBtn:disabled, #refineBtn:disabled { opacity: 0.5; cursor: wait; }
    #meta {
      padding: 4px 12px; font-size: 11px; color: #6b7280;
      background: #0a0a0a; border-bottom: 1px solid #1e1e1e; flex-shrink: 0;
    }
    #mainArea { display: flex; flex: 1; overflow: hidden; }
    #canvasWrap { flex: 1; position: relative; background: #0f0f0f; overflow: hidden; }
    #graph { width: 100%; height: 100%; display: block; cursor: grab; }
    #graph.panning { cursor: grabbing; }
    .node { cursor: pointer; }
    .node:hover circle { filter: brightness(1.5); }
    #empty {
      position: absolute; inset: 0; display: none; align-items: center;
      justify-content: center; color: #555; font-size: 13px; pointer-events: none;
    }
    #hint {
      position: absolute; bottom: 8px; left: 12px; font-size: 10px; color: #2a2a2a;
      pointer-events: none;
    }
    #detail {
      width: 300px; background: #0a0a0a; border-left: 1px solid #2a2a2a;
      padding: 14px; overflow-y: auto; display: flex; flex-direction: column; gap: 10px; flex-shrink: 0;
    }
    .sec { font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: #4b5563; font-weight: 600; }
    #detailMeta { font-size: 11px; color: #9ca3af; }
    #detailName { font-size: 15px; font-weight: 700; color: #e5e7eb; display: none; }
    #detailTypeBadge { display: none; }
    #detailDesc { color: #d1d5db; font-size: 12px; line-height: 1.5; }
    #detailFacts { font-size: 12px; }
    #detailRelations { font-size: 11px; line-height: 1.9; }
    #legend { margin-top: auto; padding-top: 10px; border-top: 1px solid #1e1e1e; font-size: 10px; color: #555; }
    .leg-row { display: flex; flex-wrap: wrap; gap: 5px 10px; margin-top: 5px; }
    .leg-item { display: flex; align-items: center; gap: 4px; }
    </style>

    <div id="root">
      <div id="toolbar">
        <select id="typeFilter">
          <option value="all">All types</option>
          <option value="team">Team</option>
          <option value="domain">Domain</option>
          <option value="topic">Topic</option>
          <option value="system">System</option>
          <option value="person">Person</option>
          <option value="process">Process</option>
          <option value="constraint">Constraint</option>
        </select>
        <input id="searchInput" placeholder="Search entities..." />
        <button id="refreshBtn">&#8635; Refresh</button>
        <button id="rebuildBtn">Rebuild</button>
        <button id="synthesizeBtn">Synthesize</button>
        <button id="refineBtn">Refine</button>
      </div>
      <div id="meta">Loading&hellip;</div>
      <div id="mainArea">
        <div id="canvasWrap">
          <svg id="graph" viewBox="0 0 2000 1100" preserveAspectRatio="xMidYMid meet"></svg>
          <div id="empty">No nodes match current filters.</div>
          <div id="hint">Scroll to zoom &bull; Drag to pan &bull; Click node to inspect &bull; Click background to deselect</div>
        </div>
        <div id="detail">
          <div class="sec">Entity Details</div>
          <div id="detailMeta">Click a node to inspect</div>
          <div id="detailName"></div>
          <div id="detailTypeBadge"></div>
          <div id="detailDesc"></div>
          <div id="detailFacts"></div>
          <div id="detailRelations"></div>
          <div id="legend">
            <div class="sec">Entity types</div>
            <div class="leg-row">
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#60a5fa"/></svg>Team</div>
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#c084fc"/></svg>Domain</div>
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#2dd4bf"/></svg>Topic</div>
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#fb923c"/></svg>System</div>
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#f472b6"/></svg>Person</div>
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#a3e635"/></svg>Process</div>
              <div class="leg-item"><svg width="10" height="10"><circle cx="5" cy="5" r="4" fill="#fbbf24"/></svg>Constraint</div>
            </div>
            <div class="sec" style="margin-top:8px;">Relation types</div>
            <div class="leg-row">
              <div class="leg-item"><svg width="20" height="6"><line x1="0" y1="3" x2="20" y2="3" stroke="#c084fc" stroke-width="1.8"/></svg>has_subtopic</div>
              <div class="leg-item"><svg width="20" height="6"><line x1="0" y1="3" x2="20" y2="3" stroke="#60a5fa" stroke-width="2"/></svg>owns</div>
              <div class="leg-item"><svg width="20" height="6"><line x1="0" y1="3" x2="20" y2="3" stroke="#fb923c" stroke-width="1.6" stroke-dasharray="6 3"/></svg>depends_on</div>
              <div class="leg-item"><svg width="20" height="6"><line x1="0" y1="3" x2="20" y2="3" stroke="#fbbf24" stroke-width="1.4" stroke-dasharray="4 3"/></svg>has_constraint</div>
              <div class="leg-item"><svg width="20" height="6"><line x1="0" y1="3" x2="20" y2="3" stroke="#2dd4bf" stroke-width="1.6"/></svg>part_of</div>
              <div class="leg-item"><svg width="20" height="6"><line x1="0" y1="3" x2="20" y2="3" stroke="#ef4444" stroke-width="2"/></svg>blocks</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
    (() => {
      const API = "__API_BASE__";
      const W = 2000, H = 1100, CX = 1000, CY = 550;
      const graph      = document.getElementById("graph");
      const typeFilter  = document.getElementById("typeFilter");
      const searchInput = document.getElementById("searchInput");
      const refreshBtn  = document.getElementById("refreshBtn");
      const rebuildBtn  = document.getElementById("rebuildBtn");
      const refineBtn   = document.getElementById("refineBtn");
      const metaEl      = document.getElementById("meta");
      const emptyEl     = document.getElementById("empty");
      const dMeta       = document.getElementById("detailMeta");
      const dName       = document.getElementById("detailName");
      const dType       = document.getElementById("detailTypeBadge");
      const dDesc       = document.getElementById("detailDesc");
      const dFacts      = document.getElementById("detailFacts");
      const dRels       = document.getElementById("detailRelations");

      const pos = new Map();
      let sel = "", raw = {nodes:[],edges:[],stats:{}};
      let sc = 1, px = 0, py = 0, pd = null;

      const esc = (s) => String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
      const hash = (s) => { let h=0; for (const c of String(s||"")) {h=(h<<5)-h+c.charCodeAt(0);h|=0;} return Math.abs(h); };
      const EC = {team:"#60a5fa",domain:"#c084fc",topic:"#2dd4bf",system:"#fb923c",person:"#f472b6",process:"#a3e635",constraint:"#fbbf24"};
      const RS = {has_subtopic:{c:"#c084fc",w:1.8,d:""},owns:{c:"#60a5fa",w:2,d:""},depends_on:{c:"#fb923c",w:1.6,d:"6 3"},has_constraint:{c:"#fbbf24",w:1.4,d:"4 3"},related_to:{c:"#6b7280",w:1,d:"3 3"},part_of:{c:"#2dd4bf",w:1.6,d:""},communicates_with:{c:"#60a5fa",w:1.2,d:"3 3"},blocks:{c:"#ef4444",w:2,d:""}};

      function findNode(el) { while(el&&el!==graph){if(el.classList&&el.classList.contains("node"))return el;el=el.parentNode;} return null; }

      function clampPan() {
        // Keep graph reachable: allow panning up to half-canvas in each direction per zoom level
        const mx = CX * sc, my = CY * sc;
        px = Math.max(-mx, Math.min(mx, px));
        py = Math.max(-my, Math.min(my, py));
      }

      function layout(nodes, edges) {
        const m = new Map();
        // Seed initial positions spread across the larger canvas
        for (const n of nodes) {
          let p = pos.get(n.id);
          if (!p) {
            const s = hash(n.id + (n.entity_type||""));
            p = { x: 160 + (s % 1680), y: 100 + ((s * 7) % 900) };
            pos.set(n.id, p);
          }
          m.set(n.id, p);
        }
        const bMargin = 160; // boundary repulsion zone
        for (let it = 0; it < 160; it++) {
          const f = new Map(nodes.map(n => [n.id, {x:0,y:0}]));
          // Node-node repulsion
          for (let i = 0; i < nodes.length; i++) {
            const a = m.get(nodes[i].id);
            for (let j = i+1; j < nodes.length; j++) {
              const b = m.get(nodes[j].id);
              const dx = a.x-b.x, dy = a.y-b.y;
              const d2 = Math.max(40, dx*dx+dy*dy);
              const r = 6000/d2;
              const fx = (dx/Math.sqrt(d2))*r, fy = (dy/Math.sqrt(d2))*r;
              f.get(nodes[i].id).x += fx; f.get(nodes[i].id).y += fy;
              f.get(nodes[j].id).x -= fx; f.get(nodes[j].id).y -= fy;
            }
          }
          // Spring attraction along edges
          for (const e of edges) {
            const a = m.get(e.source), b = m.get(e.target);
            if (!a||!b) continue;
            const dx = b.x-a.x, dy = b.y-a.y;
            const d = Math.max(1, Math.sqrt(dx*dx+dy*dy));
            const sp = (d - 130) * 0.022;
            const fx = (dx/d)*sp, fy = (dy/d)*sp;
            f.get(e.source).x += fx; f.get(e.source).y += fy;
            f.get(e.target).x -= fx; f.get(e.target).y -= fy;
          }
          // Apply forces + gravity toward center + boundary repulsion
          for (const n of nodes) {
            const p = m.get(n.id), ff = f.get(n.id);
            // Boundary repulsion — push away from all 4 walls
            if (p.x < bMargin)    ff.x += (bMargin - p.x) * 0.4;
            if (p.x > W-bMargin)  ff.x -= (p.x - (W-bMargin)) * 0.4;
            if (p.y < bMargin)    ff.y += (bMargin - p.y) * 0.4;
            if (p.y > H-bMargin)  ff.y -= (p.y - (H-bMargin)) * 0.4;
            // Gravity toward canvas center
            const gx = (CX - p.x) * 0.005;
            const gy = (CY - p.y) * 0.005;
            p.x = Math.max(120, Math.min(W-120, p.x + (ff.x + gx) * 0.24));
            p.y = Math.max(120, Math.min(H-120, p.y + (ff.y + gy) * 0.24));
          }
        }
      }

      function details(nodes, edges) {
        const n = nodes.find(x => x.id === sel);
        if (!n) {
          dMeta.textContent = "Click a node to inspect";
          dName.style.display = "none"; dType.style.display = "none";
          dDesc.textContent = ""; dFacts.innerHTML = ""; dRels.innerHTML = "";
          return;
        }
        const c = EC[n.entity_type]||"#d1d5db";
        dMeta.textContent = "Updated: " + String(n.last_updated||"").slice(0,10);
        dName.textContent = n.name||""; dName.style.display = "block";
        dType.innerHTML = "<span style='padding:2px 8px;border-radius:10px;font-size:10px;background:"+c+"22;color:"+c+";border:1px solid "+c+"44;'>"+esc(n.entity_type||"")+"</span>";
        dType.style.display = "block";
        dDesc.textContent = n.description||"";
        const ff = Array.isArray(n.facts) ? n.facts : [];
        dFacts.innerHTML = ff.length ? "<div style='font-size:10px;color:#6b7280;text-transform:uppercase;margin-bottom:4px;'>Facts</div>"+ff.map(f=>"<div style='font-size:12px;color:#d1d5db;padding:2px 0;border-bottom:1px solid #1e1e1e;'>&bull; "+esc(f)+"</div>").join("") : "";
        const rels = edges.filter(e=>e.source===n.id||e.target===n.id).slice(0,15);
        if (rels.length) {
          const items = rels.map(e=>{
            const isSrc = e.source===n.id;
            const oid = isSrc ? e.target : e.source;
            const o = nodes.find(x=>x.id===oid);
            const on = o ? o.name : oid;
            const rt = e.relation_type||"related_to";
            const rc = (RS[rt]||{}).c||"#6b7280";
            const ar = isSrc ? "\u2192" : "\u2190";
            const lb = e.label || rt.replace(/_/g," ");
            return "<div><span style='color:"+rc+";font-size:10px;'>"+esc(lb)+"</span> "+ar+" <span style='color:#d1d5db;'>"+esc(on)+"</span></div>";
          });
          dRels.innerHTML = "<div style='font-size:10px;color:#6b7280;text-transform:uppercase;margin-bottom:4px;'>Relations ("+rels.length+")</div>"+items.join("");
        } else {
          dRels.innerHTML = "<span style='color:#4b5563;font-size:11px;'>No relations yet.</span>";
        }
      }

      function render() {
        const tf = typeFilter.value||"all";
        const q = (searchInput.value||"").toLowerCase().trim();
        const nodes = raw.nodes.filter(n=>{
          if (tf!=="all" && n.entity_type!==tf) return false;
          if (q && !(n.name||"").toLowerCase().includes(q) && !(n.description||"").toLowerCase().includes(q)) return false;
          return true;
        });
        const ids = new Set(nodes.map(n=>n.id));
        const edges = raw.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));
        const st = raw.stats||{};
        metaEl.textContent = nodes.length+" entities \u2022 "+edges.length+" relations"+(st.total_entities?" ("+st.total_entities+" total)":"");
        emptyEl.style.display = nodes.length ? "none" : "flex";
        if (!nodes.length) { graph.innerHTML=""; details(nodes,edges); return; }
        layout(nodes, edges);

        const sn = new Set();
        if (sel) { sn.add(sel); edges.forEach(e=>{ if(e.source===sel)sn.add(e.target); if(e.target===sel)sn.add(e.source); }); }
        const hs = sel !== "";

        const esvg = edges.map(e=>{
          const a=pos.get(e.source), b=pos.get(e.target); if(!a||!b) return "";
          const s = RS[e.relation_type]||RS.related_to;
          const ic = e.source===sel||e.target===sel;
          const op = hs ? (ic?0.9:0.06) : 0.65;
          const mx=(a.x+b.x)/2, my=(a.y+b.y)/2;
          const lop = hs ? (ic?0.85:0) : 0.4;
          const lb = (e.relation_type||"").replace(/_/g," ");
          return "<line x1='"+a.x+"' y1='"+a.y+"' x2='"+b.x+"' y2='"+b.y+"' stroke='"+s.c+"' stroke-width='"+s.w+"' stroke-dasharray='"+s.d+"' opacity='"+op+"' />"
            + (lop>0 ? "<text x='"+mx+"' y='"+(my-3)+"' text-anchor='middle' font-size='6.5' fill='"+s.c+"' opacity='"+lop+"' pointer-events='none'>"+esc(lb)+"</text>" : "");
        }).join("");

        const nsvg = nodes.map(n=>{
          const p=pos.get(n.id); if(!p) return "";
          const deg = n.degree||0;
          const r = 8 + Math.min(12, deg*2);
          const c = EC[n.entity_type]||"#d1d5db";
          const dim = hs && !sn.has(n.id);
          const op = dim ? 0.1 : 0.92;
          const lop = dim ? 0.05 : (sel===n.id ? 1 : 0.85);
          const sk = sel===n.id ? "#fff" : "#0f0f10";
          const sw = sel===n.id ? 2.5 : 1.2;
          const nm = String(n.name||"");
          const label = nm.length>22 ? nm.slice(0,21)+"\u2026" : nm;
          return "<g class='node' data-id='"+esc(n.id)+"'>"
            + "<circle cx='"+p.x+"' cy='"+p.y+"' r='"+r+"' fill='"+c+"' opacity='"+op+"' stroke='"+sk+"' stroke-width='"+sw+"' />"
            + "<text x='"+p.x+"' y='"+(p.y+3)+"' text-anchor='middle' font-size='8' font-weight='700' fill='#ffffff' stroke='#000' stroke-width='2.5' paint-order='stroke' opacity='"+lop+"' pointer-events='none'>"+esc(label)+"</text>"
            + "<text x='"+p.x+"' y='"+(p.y+r+11)+"' text-anchor='middle' font-size='7' fill='#e2e2e2' stroke='#111' stroke-width='2' paint-order='stroke' opacity='"+(lop*0.85)+"' pointer-events='none'>"+esc(n.entity_type||"")+"</text>"
            + "</g>";
        }).join("");

        graph.innerHTML = "<g transform='translate("+px+" "+py+") scale("+sc+")'>"+esvg+nsvg+"</g>";
        details(nodes, edges);
      }

      async function load() {
        metaEl.textContent = "Loading\u2026";
        try {
          const r = await fetch(API+"/api/memory/entity-graph?active_only=true");
          const d = await r.json();
          if (!r.ok) throw new Error(d.detail||"Failed");
          raw = {nodes:d.nodes||[],edges:d.edges||[],stats:d.stats||{}};
          pos.clear(); // reset positions on fresh load so layout reruns cleanly
          render();
        } catch(e) {
          raw = {nodes:[],edges:[],stats:{}};
          graph.innerHTML = "";
          emptyEl.style.display = "flex";
          metaEl.textContent = (e&&e.message)||"Network error";
        }
      }

      // Events
      graph.addEventListener("click", (e)=>{
        if (pd&&pd.moved) return;
        const ng = findNode(e.target);
        if (!ng) { sel=""; render(); return; }
        const id = ng.getAttribute("data-id")||"";
        sel = (sel===id) ? "" : id;
        render();
      });
      graph.addEventListener("mousedown", (e)=>{
        if (findNode(e.target)) return;
        graph.classList.add("panning");
        pd = {sx:e.clientX,sy:e.clientY,px:px,py:py,moved:false};
      });
      document.addEventListener("mousemove", (e)=>{
        if (!pd) return;
        const dx=e.clientX-pd.sx, dy=e.clientY-pd.sy;
        if (Math.abs(dx)>3||Math.abs(dy)>3) pd.moved=true;
        if (!pd.moved) return;
        const rect=graph.getBoundingClientRect();
        px = pd.px + dx*(W/(rect.width||W));
        py = pd.py + dy*(H/(rect.height||H));
        clampPan();
        render();
      });
      document.addEventListener("mouseup", ()=>{ if(pd){graph.classList.remove("panning");pd=null;} });
      graph.addEventListener("wheel", (e)=>{
        e.preventDefault();
        sc = Math.max(0.5, Math.min(3, sc*(e.deltaY>0?0.92:1.08)));
        clampPan();
        render();
      }, {passive:false});

      refreshBtn.addEventListener("click", load);
      typeFilter.addEventListener("change", render);
      let debTimer=0;
      searchInput.addEventListener("input", ()=>{ clearTimeout(debTimer); debTimer=setTimeout(render,120); });
      rebuildBtn.addEventListener("click", async ()=>{
        rebuildBtn.disabled=true; rebuildBtn.textContent="Rebuilding\u2026";
        try {
          const r=await fetch(API+"/api/memory/rebuild-entity-graph",{method:"POST"});
          const d=await r.json();
          rebuildBtn.textContent=
            "Done ("+((d.entities_upserted||0))+" ent, "
            +((d.relations_upserted||0))+" rel, "
            +((d.entities_merged||0))+" merged, "
            +((d.relations_refined_added||0))+" add, "
            +((d.relations_refined_fixed||0))+" fix)";
          await load();
        } catch(e) { rebuildBtn.textContent="Error"; }
        setTimeout(()=>{ rebuildBtn.textContent="Rebuild"; rebuildBtn.disabled=false; },3000);
      });

      const synthesizeBtn = document.getElementById("synthesizeBtn");
      if (synthesizeBtn) {
        synthesizeBtn.addEventListener("click", async ()=>{
          synthesizeBtn.disabled=true; synthesizeBtn.textContent="Synthesizing\u2026";
          try {
            const r=await fetch(API+"/api/memory/synthesize-cross-source",{method:"POST"});
            const d=await r.json();
            if (d.ok===false) {
              synthesizeBtn.textContent="Error";
            } else {
              synthesizeBtn.textContent=
                "Done ("+(d.written||0)+" kb, "
                +(d.entities_upserted||0)+" ent, "
                +(d.relations_upserted||0)+" rel, "
                +(d.parents_created||0)+" groups, "
                +(d.entities_merged||0)+" merged, "
                +(d.relations_refined_added||0)+" add, "
                +(d.relations_refined_fixed||0)+" fix)";
              await load();
            }
          } catch(e) { synthesizeBtn.textContent="Error"; }
          setTimeout(()=>{ synthesizeBtn.textContent="Synthesize"; synthesizeBtn.disabled=false; },4000);
        });
      }

      if (refineBtn) {
        refineBtn.addEventListener("click", async ()=>{
          refineBtn.disabled=true; refineBtn.textContent="Refining\u2026";
          try {
            const r=await fetch(API+"/api/memory/refine-entity-graph",{method:"POST"});
            const d=await r.json();
            if (d.ok===false) {
              refineBtn.textContent="Error";
            } else {
              refineBtn.textContent=
                "Done ("+((d.entities_merged||0))+" merged, "
                +((d.relations_added||0))+" add, "
                +((d.relations_fixed||0))+" fix)";
              await load();
            }
          } catch(e) { refineBtn.textContent="Error"; }
          setTimeout(()=>{ refineBtn.textContent="Refine"; refineBtn.disabled=false; },4000);
        });
      }

      load();
    })();
    </script>
    """.replace("__API_BASE__", API_BASE)
    components.html(html_payload, height=1200, scrolling=False)


# ── Global CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
/* ── Base ── */
.stApp { background: #111111; }
/* Use full viewport width — Streamlit caps .block-container by default, leaving empty space on the right */
section.main > div,
[data-testid="stMainBlockContainer"] {
  max-width: none !important;
}
div.block-container {
  max-width: none !important;
  padding-left: max(1rem, env(safe-area-inset-left)) !important;
  padding-right: max(1rem, env(safe-area-inset-right)) !important;
}
[data-testid="stSidebar"] { background: #0a0a0a; border-right: 1px solid #2a2a2a; }
[data-testid="stSidebar"] [data-testid="stMarkdown"] { color: #d4d4d4; }
header[data-testid="stHeader"] { background: #111111; }

/* ── Activity bar ── */
.act-section {
    font-size:10px; text-transform:uppercase; letter-spacing:1.2px;
    color:#666666; padding:16px 14px 6px; font-weight:600;
}

/* ── Health bar ── */
.health-bar { display:flex; height:6px; border-radius:3px; overflow:hidden; margin:8px 0 4px; }
.health-seg { height:100%; transition:width .3s; }

/* ── Status pills ── */
.st-pill {
    display:inline-flex; align-items:center; gap:5px;
    padding:3px 10px; border-radius:12px; font-size:11.5px; font-weight:600;
    white-space:nowrap;
}

/* ── Task table ── */
.task-table { width:100%; border-collapse:collapse; font-size:12.5px; font-family:'Segoe UI',sans-serif; }
.task-table th {
    background:#0a0a0a; color:#999999; padding:10px 8px; text-align:left;
    font-size:10.5px; text-transform:uppercase; letter-spacing:.8px; font-weight:600;
    border-bottom:2px solid #2a2a2a; position:sticky; top:0; z-index:1;
}
.task-table td {
    padding:10px 8px; border-bottom:1px solid #2a2a2a; color:#d4d4d4;
    vertical-align:top; word-wrap:break-word; overflow-wrap:break-word;
}
.task-table tr:hover td { background:#1a1a1a; }
.task-table td:nth-child(1) { width:32px; color:#666666; font-size:11px; }
.task-table td:nth-child(4) { width:40px; text-align:center; }
.task-table td:nth-child(5) { width:130px; }
.task-table td:nth-child(6) { width:64px; }
.task-table .meta { font-size:10px; color:#666666; margin-top:2px; }
.task-table .next-steps { margin-top:5px; font-size:11.5px; color:#999999; }
.task-table .next-steps b { color:#e09956; }
.task-table a { color:#e09956; text-decoration:none; }
.task-table a:hover { text-decoration:underline; }
.task-table .def-text { color:#999999; font-size:12px; }

/* ── Fixed chat panel — target column that contains the .chat-panel-root marker ── */
[data-testid="stColumn"]:has(.chat-panel-root) {
    position: sticky;
    top: 0;
    align-self: flex-start;
    height: 100vh;
    overflow-y: auto;
    background: #0a0a0a;
    border-left: 1px solid #2a2a2a;
    padding: 12px 8px 8px !important;
    z-index: 50;
}
.chat-panel-root { /* marker element, no visual */ }

.chat-panel-title {
    font-size:11px; text-transform:uppercase; letter-spacing:1px;
    color:#666666; font-weight:600; padding-bottom:6px; margin-bottom:6px;
    border-bottom:1px solid #2a2a2a;
    display:flex; align-items:center; gap:8px;
}
.chat-panel-title .badge {
    background:#222222; color:#999999; padding:1px 8px;
    border-radius:10px; font-size:10px;
}
.chat-msg { padding:5px 0; font-size:12.5px; line-height:1.45; }
.chat-role { font-weight:700; margin-right:6px; }
.chat-role.user { color:#e09956; }
.chat-role.copilot { color:#d4a843; }
.chat-role.system { color:#666666; }
.chat-text { color:#d4d4d4; white-space:pre-wrap; word-break:break-word; }

/* ── Follow-ups in chat panel ── */
.fu-title {
    font-size:10px; text-transform:uppercase; letter-spacing:1px;
    color:#666666; font-weight:600; padding:8px 0 4px;
    border-top:1px solid #2a2a2a; margin-top:6px;
}
.fu-item {
    font-size:11.5px; color:#999999; padding:3px 0;
    border-bottom:1px solid #111111;
}

/* ── Panel styling ── */
.panel-title {
    font-size:11px; text-transform:uppercase; letter-spacing:1px;
    color:#666666; font-weight:600; margin-bottom:10px;
    display:flex; align-items:center; gap:8px;
}
.panel-title .badge {
    background:#222222; color:#999999; padding:1px 8px;
    border-radius:10px; font-size:10px;
}
</style>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# DATA FETCH
# ══════════════════════════════════════════════════════════════════════════════
tasks_data = api_get("/api/tasks")
if tasks_data is None:
    st.error("Cannot reach backend. Make sure FastAPI is running on port 8001.")
    st.code("source .venv/bin/activate && python -m app.main", language="bash")
    st.stop()

sprint_name = tasks_data.get("sprint_name", "-")
tasks = tasks_data.get("tasks", [])
followups_data = api_get("/api/followups")
followups = followups_data.get("follow_ups", []) if followups_data else []


# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR — Activity Bar
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("""
    <div style="padding:12px 8px 4px; display:flex; align-items:center; gap:10px;">
        <span style="font-size:22px;">🚀</span>
        <div>
            <div style="font-size:15px; font-weight:700; color:#d4d4d4;">Sprint Engine</div>
            <div style="font-size:10px; color:#666666;">local-first sprint workspace</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<div class="act-section">Navigation</div>', unsafe_allow_html=True)

    for key, label in {
        "tasks": "📋  Tasks",
        "report": "📝  Report",
        "plan": "📄  Plan",
        "knowledge_alt": "🧠  Knowledge Graph",
        "content_generator": "✍️  Content Generator",
        "prds": "📄  PRDs",
    }.items():
        if st.button(label, key=f"nav_{key}", use_container_width=True,
                     type="primary" if st.session_state.active_view == key else "secondary"):
            st.session_state.active_view = key
            st.rerun()

    st.markdown('<div class="act-section">Actions</div>', unsafe_allow_html=True)

    with st.expander("🔄 Initialize", expanded=False):
        init_mode = st.selectbox(
            "Mode", ["sync_missing", "destructive"],
            format_func=lambda m: "Sync Missing" if m == "sync_missing" else "Destructive",
            label_visibility="collapsed",
        )
        c1, c2 = st.columns(2)
        with c1:
            if st.button("Run", key="init_run", use_container_width=True):
                confirm = "RESET" if init_mode == "destructive" else ""
                data, ok = api_post("/api/initialize", {"mode": init_mode, "confirm_text": confirm})
                if ok:
                    msg = f"Initialized. Tasks: {data.get('task_count', '?')}"
                    st.toast(msg, icon="✅"); add_chat("system", msg); st.rerun()
                else:
                    st.toast(data.get("detail", "Failed"), icon="❌")
        with c2:
            if st.button("Undo", key="init_undo", use_container_width=True):
                data, ok = api_post("/api/initialize/undo")
                if ok:
                    msg = f"Undo restored. Tasks: {data.get('task_count', '?')}"
                    st.toast(msg, icon="↩️"); add_chat("system", msg); st.rerun()
                else:
                    st.toast(data.get("detail", "Failed"), icon="❌")

    with st.expander("📥 Import DOCX", expanded=False):
        docx_path = st.text_input("Path", placeholder="/Users/.../Sprint Plan.docx", label_visibility="collapsed")
        if st.button("Import", key="import_run", use_container_width=True):
            if docx_path.strip():
                add_chat("system", f"Importing: {docx_path}")
                data, ok = api_post("/api/import-docx-plan", {"file_path": docx_path, "auto_initialize": True})
                if ok:
                    merge = ""
                    if data.get("added_count", 0) or data.get("synced_count", 0):
                        merge = f" +{data['added_count']} synced:{data['synced_count']}"
                    msg = f"Imported ({data.get('source', '?')}). Tasks: {data.get('task_count', '?')}{merge}"
                    st.toast(msg, icon="✅"); add_chat("copilot", msg); st.rerun()
                else:
                    st.toast(data.get("detail", "Failed"), icon="❌")
            else:
                st.toast("Enter a file path.", icon="⚠️")

    with st.expander("📊 Export", expanded=False):
        if st.button("Generate Table File", key="gen_table", use_container_width=True):
            data, ok = api_post("/api/generate-table")
            st.toast(f"Saved: {data.get('path', '')}" if ok else "Failed", icon="📄" if ok else "❌")


# ══════════════════════════════════════════════════════════════════════════════
# HEALTH BAR (top strip)
# ══════════════════════════════════════════════════════════════════════════════
def render_health_bar(tasks_list):
    total = len(tasks_list)
    if not total:
        return
    counts = {}
    for t in tasks_list:
        s = t.get("status", "not_started")
        counts[s] = counts.get(s, 0) + 1
    done = counts.get("done", 0)
    in_prog = counts.get("in_progress", 0)
    blocked = counts.get("blocked", 0)
    on_hold = counts.get("on_hold", 0)
    other = total - done - in_prog - blocked - on_hold
    segments = ""
    for count, color in [
        (done, "#51cf66"), (in_prog, "#ffd43b"), (blocked, "#ff6b6b"),
        (on_hold, "#a9a9a9"), (other, "#333333"),
    ]:
        if count > 0:
            segments += f'<div class="health-seg" style="width:{count/total*100}%;background:{color};"></div>'
    st.markdown(f"""
    <div style="display:flex; align-items:center; gap:12px; padding:2px 0 6px;">
        <span style="font-size:13px; font-weight:600; color:#d4d4d4;">{esc(sprint_name)}</span>
        <div class="health-bar" style="flex:1;">{segments}</div>
        <div style="display:flex; gap:10px; font-size:11px; color:#999999;">
            <span>✅ {done}</span><span>🚧 {in_prog}</span><span>⛔ {blocked}</span>
            <span>⏸️ {on_hold}</span><span>⚪ {other}</span>
            <span style="color:#666666;">({total} total)</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

render_health_bar(tasks)


# ══════════════════════════════════════════════════════════════════════════════
# FULL-WIDTH: Views that bypass two-column layout
# ══════════════════════════════════════════════════════════════════════════════
if st.session_state.active_view == "knowledge_alt":
    render_streamlit_knowledge_alt()
    st.stop()

if st.session_state.active_view == "content_generator":
    render_streamlit_content_generator()
    st.stop()

if st.session_state.active_view == "prds":
    render_streamlit_prds()
    st.stop()

# ══════════════════════════════════════════════════════════════════════════════
# TWO-COLUMN LAYOUT: Main Content (left) + Chat Panel (right)
# ══════════════════════════════════════════════════════════════════════════════
main_col, chat_col = st.columns([3, 1], gap="medium")

# ──────────────────────────────────────────────────────────────────────────────
# LEFT: Main content area
# ──────────────────────────────────────────────────────────────────────────────
with main_col:

    # ── VIEW: TASKS ──────────────────────────────────────────────────────────
    if st.session_state.active_view == "tasks":
        sort_col, _ = st.columns([1, 4])
        with sort_col:
            st.session_state.table_sort = st.selectbox(
                "Sort", ["status", "plan", "updated"],
                format_func=lambda m: {"status": "Status Priority", "plan": "Plan Order", "updated": "Latest Updated"}[m],
                index=["status", "plan", "updated"].index(st.session_state.table_sort),
                label_visibility="collapsed",
            )

        sorted_tasks = list(tasks)
        sm = st.session_state.table_sort
        if sm == "status":
            sorted_tasks.sort(key=lambda t: (STATUS_RANK.get(t.get("status", ""), 9), t.get("task_name", "")))
        elif sm == "updated":
            sorted_tasks.sort(key=lambda t: t.get("last_updated_at", ""), reverse=True)

        if not sorted_tasks:
            st.info("No tasks yet. Import a DOCX or initialize from sprint_plan.md.")
        else:
            rows_html = ""
            for i, task in enumerate(sorted_tasks, 1):
                light = LIGHT_EMOJI.get(task.get("traffic_light", ""), "-")
                status_raw = task.get("status", "not_started")
                s_color = STATUS_COLORS.get(status_raw, "#868e96")
                s_emoji = STATUS_EMOJI.get(status_raw, "")
                s_text = pretty_status(status_raw)

                try:
                    dt = datetime.fromisoformat(task.get("last_updated_at", "").replace("Z", "+00:00"))
                    updated_str = dt.strftime("%b %d")
                except Exception:
                    updated_str = "-"

                task_name = esc(task.get("task_name", "-"))
                task_link = (task.get("task_link", "") or "").strip()
                task_cell = f'{task_name} <a href="{esc(task_link)}" target="_blank" title="{esc(task_link)}">🔗</a>' if task_link else task_name

                definition = esc(task.get("definition", task.get("task_name", "-")))
                eta = esc(pretty_eta(task.get("eta", "")))

                lu_raw = (task.get("latest_update", "") or "").strip()
                if lu_raw:
                    ns_match = _re.search(r"(?:\n\s*\n|\s+)?(?:\*\*)?Next Steps?:\s*(.+)$", lu_raw, _re.IGNORECASE | _re.DOTALL)
                    if ns_match:
                        summary = esc(lu_raw[:ns_match.start()].strip().replace("**", ""))
                        next_steps = esc(ns_match.group(1).strip().replace("**", ""))
                        lu_cell = f"{summary}<div class='next-steps'><b>Next Steps:</b> {next_steps}</div>"
                    else:
                        lu_cell = esc(lu_raw)
                else:
                    lu_cell = "<span style='color:#333333;'>-</span>"

                pill = f'<span class="st-pill" style="background:{s_color}22;color:{s_color};border:1px solid {s_color}44;">{s_emoji} {s_text}</span>'
                status_cell = f"{pill}<div class='meta'>Updated: {esc(updated_str)}</div>"
                rows_html += f"<tr><td>{i}</td><td>{task_cell}</td><td class='def-text'>{definition}</td><td>{light}</td><td>{status_cell}</td><td>{eta}</td><td>{lu_cell}</td></tr>"

            st.markdown(f"""
            <div style="overflow-x:auto;">
            <table class="task-table"><thead><tr>
            <th>#</th><th>Task</th><th>Definition</th><th></th><th>Status</th><th>ETA</th><th>Latest Update</th>
            </tr></thead><tbody>{rows_html}</tbody></table>
            </div>
            """, unsafe_allow_html=True)

    # ── VIEW: REPORT ─────────────────────────────────────────────────────────
    elif st.session_state.active_view == "report":
        if not st.session_state.report_loaded:
            rdata = api_get("/api/report")
            st.session_state.report_content = rdata.get("content", "") if rdata else ""
            st.session_state.report_loaded = True

        c1, c2, c3 = st.columns([1, 1, 4])
        with c1:
            if st.button("Generate Report", use_container_width=True):
                with st.spinner("Generating..."):
                    data, ok = api_post("/api/report/generate")
                    if ok:
                        st.session_state.report_content = data.get("content", "")
                        st.toast("Report generated", icon="✅"); st.rerun()
                    else:
                        st.toast(data.get("detail", "Failed"), icon="❌")
        with c2:
            if st.button("Save Report", use_container_width=True):
                data, ok = api_post("/api/report/save", {"content": st.session_state.report_content})
                st.toast("Saved" if ok else "Failed", icon="💾" if ok else "❌")

        view_mode = st.radio("Mode", ["Edit", "Preview"], horizontal=True, label_visibility="collapsed")
        if view_mode == "Edit":
            st.session_state.report_content = st.text_area(
                "Report", value=st.session_state.report_content, height=550, label_visibility="collapsed",
            )
        else:
            st.markdown(st.session_state.report_content or "*No report content yet.*")

    # ── VIEW: PLAN ───────────────────────────────────────────────────────────
    elif st.session_state.active_view == "plan":
        plan_data = api_get("/api/plan")
        if plan_data and plan_data.get("exists"):
            st.code(plan_data.get("content", ""), language="markdown")
        else:
            st.info("No sprint_plan.md found yet. Import a DOCX to create one.")

    # knowledge_alt is rendered full-width above (before st.columns)


# ──────────────────────────────────────────────────────────────────────────────
# RIGHT: Chat panel (full height alongside main content)
# ──────────────────────────────────────────────────────────────────────────────
with chat_col:
    # Marker element for CSS :has() selector to make this column sticky
    st.markdown('<div class="chat-panel-root"></div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="chat-panel-title">Terminal <span class="badge">Chat</span></div>',
        unsafe_allow_html=True,
    )

    # Chat history — fills available height, input stays at bottom
    chat_container = st.container(height=440)
    with chat_container:
        for entry in st.session_state.chat_history:
            role = entry["role"]
            text = entry["text"]
            role_class = {"you": "user", "copilot": "copilot"}.get(role, "system")
            role_label = {"you": "You:", "copilot": "Copilot:"}.get(role, "System:")
            st.markdown(
                f'<div class="chat-msg"><span class="chat-role {role_class}">{role_label}</span>'
                f'<span class="chat-text">{esc(text)}</span></div>',
                unsafe_allow_html=True,
            )

    # Mode selector
    chat_mode = st.selectbox(
        "Mode", ["auto", "query", "update"],
        format_func=lambda m: {"auto": "Auto", "query": "Query", "update": "Update"}[m],
        label_visibility="collapsed",
    )

    # Chat input — compact 2-3 line text area + send button
    user_input = st.text_area(
        "Message",
        placeholder="Type daily update or ask a question...",
        height=68,
        label_visibility="collapsed",
        key="chat_input_area",
    )
    if st.button("Send", key="send_btn", use_container_width=True, type="primary"):
        text = (user_input or "").strip()
        if text:
            add_chat("you", text)
            data, ok = api_post("/api/chat", {"message": text, "mode": chat_mode})
            if ok:
                add_chat("copilot", data.get("answer", "No response."))
                for t in data.get("changed_tasks", []):
                    light = LIGHT_EMOJI.get(t.get("traffic_light", ""), "")
                    add_chat("system", f"- {t['task_name']}: {pretty_status(t.get('status', ''))} {light}")
            else:
                add_chat("copilot", data.get("detail", "Something went wrong."))
            st.rerun()

    # Follow-ups section inside chat panel
    if followups:
        st.markdown(
            f'<div class="fu-title">Follow-ups <span style="background:#2a2a2a;color:#999999;padding:1px 6px;border-radius:8px;font-size:9px;">{len(followups)}</span></div>',
            unsafe_allow_html=True,
        )
        for fu in followups:
            st.markdown(f'<div class="fu-item">{esc(fu)}</div>', unsafe_allow_html=True)
